ARRAYS 1D PARTE 1:
1. Crea un array_1 lleno ceros con una longitud de 8 elementos.
2. Haz que todos los elementos de este array sean igual a 2
3. Crea un array_2 que contenga todos los números pares del 1 al 10.
4. Suma todos los elementos del array_2 usando un bucle y después usando un método
de numpy. Compara los resultados
5. Revierte array_2 y guárdalo en una variable independiente.
6. Encuentra los elementos comunes entre array_1 y array_2 y entre array_2 y
array_2_revertido
 (Pista: Investiga el uso de intersect1d() de numpy)
7. Crea un arrays lleno de 1s con una longitud dada por el usuario

1. Crea un array_1 lleno ceros con una longitud de 8 elementos.

In [1]:
#importar
import numpy as np

#crear array a zeros
array_1 = np.zeros((8))
print(array_1)

[0. 0. 0. 0. 0. 0. 0. 0.]


2. Haz que todos los elementos de este array sean igual a 2

In [2]:
#todo a 2
array_1[:] = 2
print(array_1) 

[2. 2. 2. 2. 2. 2. 2. 2.]


3. Crea un array_2 que contenga todos los números pares del 1 al 10.

In [3]:
# pares de 2 a 10
array_2 = np.arange(2,11,2)
print(array_2)

[ 2  4  6  8 10]


4. Suma todos los elementos del array_2 usando un bucle y después usando un método
de numpy. Compara los resultados

In [4]:
# recorrer con bucle y calcular total
total = 0
for i in array_2:
    total += i
print(total)

30


In [5]:
total = sum(array_2)
print(total)

30


5. Revierte array_2 y guárdalo en una variable independiente.

In [6]:
array_3 = np.copy(array_2[::-1])
print(array_2)
print(array_3)
#array_2[:] = 2
print(array_2)
print(array_3)

[ 2  4  6  8 10]
[10  8  6  4  2]
[ 2  4  6  8 10]
[10  8  6  4  2]


6. Encuentra los elementos comunes entre array_1 y array_2 y entre array_2 y
array_2_revertido
 (Pista: Investiga el uso de intersect1d() de numpy)

In [7]:
inter_1 = np.intersect1d(array_1,array_2)
inter_2 = np.intersect1d(array_2,array_3)
print(inter_1,"\n", inter_2)

[2.] 
 [ 2  4  6  8 10]


7. Crea un arrays lleno de 1s con una longitud dada por el usuario

In [8]:
# longitud = int(input("indique la longitud del array: "))
longitud = 10
array_user = np.ones(longitud)
print (array_user)


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
