ARRAYS 1D PARTE 1:
1. Crea un array_1 lleno ceros con una longitud de 8 elementos.
2. Haz que todos los elementos de este array sean igual a 2
3. Crea un array_2 que contenga todos los números pares del 1 al 10.
4. Suma todos los elementos del array_2 usando un bucle y después usando un método
de numpy. Compara los resultados
5. Revierte array_2 y guárdalo en una variable independiente.
6. Encuentra los elementos comunes entre array_1 y array_2 y entre array_2 y
array_2_revertido
 (Pista: Investiga el uso de intersect1d() de numpy)
7. Crea un arrays lleno de 1s con una longitud dada por el usuario

In [1]:
import numpy as np
array_1 = np.zeros((8))
print(array_1)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [2]:
array_1[:] = 8
print(array_1) 

[8. 8. 8. 8. 8. 8. 8. 8.]


In [4]:
array_2 = np.arange(2,11,2)
print(array_2)

[ 2  4  6  8 10]


In [6]:
total = 0
for i in array_2:
    total += i
print(total)

30


In [8]:
total = sum(array_2)
print(total)

30


In [9]:
array_3 = array_2[::-1]
print(array_3)

[10  8  6  4  2]


In [11]:
inter_1 = np.intersect1d(array_1,array_2)
inter_2 = np.intersect1d(array_2,array_3)
print(inter_1,"\n", inter_2)

[8.] 
 [ 2  4  6  8 10]


In [ ]:
longitud = int(input("indique la longitud del array: "))
array_user = np.ones(longitud)
print (array_user)


[0. 0. 0. 0. 0.]
